import { Animal } from '../app/core/models/interfaces/animal';

export const ANIMALS: Animal[] = [
  {
    id: 1,
    name: 'Sabuś',
    description: 'Photo by Pixabay from Pexels',
    image: ['assets/product/product-1.webp', 'assets/product/product-2.webp', 'assets/product/product-3.webp'],
    species: 'boxer',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 2,
    name: 'Wersa',
    description: 'Photo by rawpixel.com from Pexels',
    image: ['assets/product/product-2.webp', 'assets/product/product-3.webp', 'assets/product/product-4.webp'],
    species: 'components',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 3,
    name: 'Budna',
    description: 'Photo by Dominika Roseclay from Pexels',
    image: ['assets/product/product-3.webp', 'assets/product/product-4.webp', 'assets/product/product-5.webp'],
    species: 'components',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 4,
    name: 'Kruser',
    description: 'Photo by Joe from Pexels',
    image: ['assets/product/product-4.webp', 'assets/product/product-5.webp', 'assets/product/product-6.webp'],
    species: 'accessories',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 5,
    name: 'Bajk',
    description: 'Photo by Pixabay from Pexels',
    image: ['assets/product/product-5.webp', 'assets/product/product-6.webp', 'assets/product/product-7.webp'],
    species: 'accessories',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 6,
    name: 'Blu',
    description: 'Photo by Helena Lopes from Pexels',
    image: ['assets/product/product-6.webp', 'assets/product/product-7.webp', 'assets/product/product-8.webp'],
    species: 'accessories',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 7,
    name: 'Setli',
    description: 'Photo by Pixabay from Pexels',
    image: ['assets/product/product-7.webp', 'assets/product/product-8.webp', 'assets/product/product-9.webp'],
    species: 'components',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 8,
    name: 'Sabu',
    description: 'Photo by Wojciech Kumpicki from Pexels',
    image: ['assets/product/product-8.webp', 'assets/product/product-9.webp', 'assets/product/product-10.webp'],
    species: 'bikes',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 9,
    name: 'Spid',
    description: 'Photo by EVG photos from Pexels',
    image: ['assets/product/product-9.webp', 'assets/product/product-10.webp', 'assets/product/product-1.webp'],
    species: 'accessories',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  },
  {
    id: 10,
    name: 'Sadi',
    description: 'Photo by Pixabay from Pexels',
    image: ['assets/product/product-10.webp', 'assets/product/product-1.webp', 'assets/product/product-2.webp'],
    species: 'accessories',
    age: 7,
    timeVisit: 2,
    weight: 6,
    size: 'medium',
    character: ['energetic', 'shy'],
    descAnimal: 'Taker is energetic and likes to play with toys, especially his tennis ball. Tucker is a little nervous meeting new people, but he is a sweetheart once he warms up.'
  }
];
